import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Head from 'next/head'; // Import the Head component
import Script from 'next/script'; // Import the Script component
// import useMetaPixel from '@/lib/useMetaPixel'



const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NicheNod",
  description: "Generated by BricAI",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}
           {/* Add the Clarity script within the Head component */}
           
           <Script id="clarity-script" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "n8czxqyk7g");
          `}
        </Script>
        </body>
      </html>
    </ClerkProvider>
  );
}
